version: '3'

tasks:
  default:
    cmds:
      - task --list

  lint:
    desc: lint and format code
    cmds:
      - cargo fmt
      - cargo clippy --fix --allow-dirty --allow-staged --workspace
      - leptosfmt '**/*.rs$'

  test:
    desc: Run test all workspace
    cmds:
      - cargo nextest run --workspace {{.CLI_ARGS}}

  test:e2e:
    desc: Run Playwright browser tests
    cmds:
      - npx playwright test {{.CLI_ARGS}}

  test:e2e:ui:
    desc: Run Playwright browser tests with interactive UI
    cmds:
      - npx playwright test --ui
