version: '3'

tasks:
  default:
    cmds:
      - task --list

  lint:
    desc: lint and format code
    cmds:
      - cargo fmt
      - cargo clippy --fix --allow-dirty --allow-staged --workspace
      - leptosfmt '**/*.rs$'

  test:
    desc: Run test all workspace
    cmds:
      - cargo nextest run --workspace {{.CLI_ARGS}}
