use immutable::Im;

use crate::sketch::Point2;

/// Edge is generated by sketch. it is 3D based on sketch's attached target.
pub struct SketchEdge {
    pub start: Im<Point2>,
    pub end: Im<Point2>,

    _immutable: (),
}

impl SketchEdge {
    /// Get a new [SketchEdge]
    pub fn new(start: &Point2, end: &Point2) -> Self {
        SketchEdge {
            start: start.clone().into(),
            end: end.clone().into(),
            _immutable: (),
        }
    }
}
